format = """
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$directory\
$vcsh\
$fossil_branch\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$sudo\
$cmd_duration\
$jobs\
$battery\
$time\
$status\
$os\
$container\
$shell\
$character"""

[character]
success_symbol = '[➜](bold green)'
error_symbol = '[➜](bold red)'

# command_timeout = 1000
[custom.chezmoi_status]
command = "~/.scripts/chezmoi_status.sh"
when = true
ignore_timeout = true
